### ISSUE TITLE
Question about Special Pages

### ISSUE THREAD

**Issue by Programazing** [jhu247/minimal-academic#13]
If I want to make a special page that's not displaying a list, such as Contact, do I have to make a layout in the theme for every page I want to make?

What I've basically done is created a new folder in Layout called Contact and placed in a list.html that mimics the about page. Though I made a new partial called Contact_Content.html which houses the html for the form.

**Comment by theorangepotato** [comment]
You don't have to make the layout in the theme. There is a `layout/` folder in the root of your Hugo directory which is made for this use case (i.e. site-specific pages, as opposed to theme-specific pages). But yes, as far as I know that is essentially the process.

For reference, something like the following should work, (assuming you are in your Hugo root):

```bash
cp -r themes/minimal-academic/layouts/about layouts/contact
hugo new contact/_index.md

# To optionally set up page. Otherwise, you might have to set the hero_image by hand.
cp content/about/_index.md content/contact/_index.md
```
