### ISSUE TITLE
Submenu Request

### ISSUE THREAD

**Issue by Programazing** [jhu247/minimal-academic#14]
I was reading through the Hugo community and the submenu examples but I wasn't too sure how to edit masthead_nav to create submenus.

I was hoping to get a little help.

**Comment by theorangepotato** [comment]
With commit 7ecfa48, masthead_nav now generates menus from config.toml. I don't know if integrating submenus as a part of standard minimal-academic is within scope of the project, but if you could get it to generate cleanly from the TOML, that'd be pretty cool.

Anyway, to your specific request, can you give any more details? Like, examples you are trying to implement, or difficulties you are having? In general, you can implement custom menus by writing them between the `<nav></nav>` tags. For instance, before the latest PR, masthead_nav looked like this:

```html
<div class="navbar-hero">
	<nav>
		<a href="/">Home</a>&nbsp&nbsp•&nbsp&nbsp
		<a href="/projects">Projects</a>&nbsp&nbsp•&nbsp&nbsp
		<a href="/blog">Blog</a>&nbsp&nbsp•&nbsp&nbsp
		<a href="/about">About</a>
	</nav>
</div>
```

I assume the submenus will have some HTML containers and hidden `<div>`s that display with CSS rules, so all of the wrappers and stuff can go within the `<nav>`s, and you can add the CSS rules wherever (either inline or in `themes/minimal-academic/layouts/index.css`, as you see fit).

**Comment by Programazing** [comment]
I was just trying to figure out how to add submenus, to be honest. I'm working nights and weekends for a while and have barely had time to learn Hugo so I don't really know much about the layout.

**Comment by theorangepotato** [comment]
There currently isn't a Hugo way to do this, support for that would have to be added to this theme. If you want this, you'll have to build it ad-hoc. Take a look at [this](https://github.com/diegodarlan/html-css-pure-dropdown-menu) for inspiration. Just like there are `<nav>` tags there, you would put all of the HTML within those between the `<nav>` tags in masthead_nav.html. You can drop a lot of the formatting and stuff if you don't want it, but you'd have to make sure the CSS you need gets in there.

If you want a less fancy, just nuts and bolts example, you can check out the third example [here](http://mrbool.com/how-to-create-menu-with-submenu-using-css-html/26146). Good luck!
