### ISSUE TITLE
Hero Image does not display on Home page. 

### ISSUE THREAD

**Issue by band** [jhu247/minimal-academic#17]
The title says it all. The background image (hero.jpg) does not display on the Home page, but it does on other pages. Current implementation is at https://praxislab.netlify.com/ . Click on one of the blog posts to see what I think should be showing up on the Home page as well.

I tried the code suggestion on Issue #15 but it does not seem to work. I am not sure why the Home page index.html contains /img/nil and the other pages have /img/hero.jpg. I think there is much I do not understand on how the public html pages get generated. Or configured?

I will continue to explore the hugo-verse.

**Comment by theorangepotato** [comment]
So, if you go to your root Hugo folder (not the root of the theme folder), and check `content/_index.md` it should be populated with the following:

```yaml
---
hero_image: "hero.jpg"

---
```

This is the file that defines the metadata for the homepage, so if this file is missing or blank, you will experience the same issue you have described here. You can see where this is defined in the [exampleSite](https://github.com/jhu247/minimal-academic/blob/master/exampleSite/content/_index.md) folder.

Let me know if that helped!
