### ISSUE TITLE
favicons don't seem to be rendering on web

### ISSUE THREAD

**Issue by cmaerzluft** [jhu247/minimal-academic#4]
The favicon for github, linken, etc work when I preview locally but when I push to netlify they don't seem to render... 
![screen shot 2018-08-28 at 1 42 13 pm](https://user-images.githubusercontent.com/9489362/44749717-38ec6e00-aac8-11e8-87ff-19cdf60644a6.png)

**Comment by jhu247** [comment]
Hi @cmaerzluft, some things that you can check to debug:
- check the netlify build log and check for any errors
- inspect the page that you've deployed and see if there are any errors
- run the `hugo` command locally and check the generated `public` directory - does the HTML pages have the favicons? for example, `<i class="fa fa-instagram"></i>`

**Comment by jhu247** [comment]
Oops, didn't mean to close.

**Comment by cmaerzluft** [comment]
Oh, I think this is a Chrome issue. They seem to appear on Safari and firefox.
